package com.informatica.wsh;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebServiceClient(wsdlLocation="http://localhost:7333/wsh/services/BatchServices/DataIntegration?WSDL",
  targetNamespace="http://www.informatica.com/wsh", name="DataIntegrationService")
public class DataIntegrationService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.informatica.wsh.DataIntegrationService");
      URL baseUrl = DataIntegrationService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            DataIntegrationService.class.getResource("http://localhost:7333/wsh/services/BatchServices/DataIntegration?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://localhost:7333/wsh/services/BatchServices/DataIntegration?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "localhost:7333/wsh/services/BatchServices/DataIntegration?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://localhost:7333/wsh/services/BatchServices/DataIntegration?WSDL",
          e);
    }
    String m_wsdlurl = null;
    if(wsdlLocationURL != null) {
      m_wsdlurl = wsdlLocationURL.toString();
    }

 //   System.out.println("wsdl url =>" + m_wsdlurl + "<.");

  }

  public DataIntegrationService()
  {
    super(wsdlLocationURL,
          new QName("http://www.informatica.com/wsh", "DataIntegrationService"));
  }

  public DataIntegrationService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="DataIntegration")
  public com.informatica.wsh.DataIntegrationInterface getDataIntegration()
  {
    return (com.informatica.wsh.DataIntegrationInterface) super.getPort(new QName("http://www.informatica.com/wsh",
                                                                                  "DataIntegration"),
                                                                        com.informatica.wsh.DataIntegrationInterface.class);
  }

  @WebEndpoint(name="DataIntegration")
  public com.informatica.wsh.DataIntegrationInterface getDataIntegration(WebServiceFeature... features)
  {
    return (com.informatica.wsh.DataIntegrationInterface) super.getPort(new QName("http://www.informatica.com/wsh",
                                                                                  "DataIntegration"),
                                                                        com.informatica.wsh.DataIntegrationInterface.class,
                                                                        features);
  }
}
