package com.informatica.wsh;

import javax.xml.ws.WebFault;

@WebFault(faultBean="com.informatica.wsh.FaultDetails", targetNamespace="http://www.informatica.com/wsh",
  name="WSHFaultDetails")
public class Fault
  extends Exception
{
  private FaultDetails faultInfo;

  public Fault(String message, FaultDetails faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public Fault(String message, FaultDetails faultInfo, Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public FaultDetails getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(FaultDetails faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)
