package com.informatica.wsh;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://someserver.somewhere.nl:7333/wsh/services/Metadata?wsdl",
  targetNamespace="http://www.informatica.com/wsh", name="MetadataInterface")
@XmlSeeAlso(
  { ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface MetadataInterface
{
  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.informatica.com/wsh/MetadataInterface/LoginRequest", fault =
      { @FaultAction(value="http://www.informatica.com/wsh/MetadataInterface/login/Fault/Fault",
          className = Fault.class) }, output="http://www.informatica.com/wsh/MetadataInterface/LoginResponse")
  @WebResult(targetNamespace="http://www.informatica.com/wsh", partName="param",
    name="LoginReturn")
  public String login(@WebParam(targetNamespace="http://www.informatica.com/wsh",
      partName="param", name="Login")
    LoginRequest param, @WebParam(targetNamespace="http://www.informatica.com/wsh",
      partName="Context", name="Context", header=true, mode=Mode.OUT)
    Holder<SessionHeader> Context)
    throws Fault;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.informatica.com/wsh/MetadataInterface/LogoutRequest", fault =
      { @FaultAction(value="http://www.informatica.com/wsh/MetadataInterface/logout/Fault/Fault",
          className = Fault.class) }, output="http://www.informatica.com/wsh/MetadataInterface/LogoutResponse")
  @WebResult(targetNamespace="http://www.informatica.com/wsh", partName="param",
    name="LogoutReturn")
  public VoidResponse logout(@WebParam(targetNamespace="http://www.informatica.com/wsh",
      partName="param", name="Logout")
    VoidRequest param, @WebParam(targetNamespace="http://www.informatica.com/wsh",
      partName="Context", name="Context", header=true)
    SessionHeader Context)
    throws Fault;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.informatica.com/wsh/MetadataInterface/GetAllFoldersRequest", fault =
      { @FaultAction(value="http://www.informatica.com/wsh/MetadataInterface/getAllFolders/Fault/Fault",
          className = Fault.class) }, output="http://www.informatica.com/wsh/MetadataInterface/GetAllFoldersResponse")
  @WebResult(targetNamespace="http://www.informatica.com/wsh", partName="param",
    name="GetAllFoldersReturn")
  public com.informatica.wsh.FolderInfoArray getAllFolders(@WebParam(targetNamespace="http://www.informatica.com/wsh",
      partName="param", name="GetAllFolders")
    VoidRequest param, @WebParam(targetNamespace="http://www.informatica.com/wsh",
      partName="Context", name="Context", header=true)
    SessionHeader Context)
    throws Fault;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.informatica.com/wsh/MetadataInterface/GetAllWorkflowsRequest", fault =
      { @FaultAction(value="http://www.informatica.com/wsh/MetadataInterface/getAllWorkflows/Fault/Fault",
          className = Fault.class) }, output="http://www.informatica.com/wsh/MetadataInterface/GetAllWorkflowsResponse")
  @WebResult(targetNamespace="http://www.informatica.com/wsh", partName="param",
    name="GetAllWorkflowsReturn")
  public com.informatica.wsh.WorkflowInfoArray getAllWorkflows(@WebParam(targetNamespace="http://www.informatica.com/wsh",
      partName="param", name="GetAllWorkflows")
    com.informatica.wsh.FolderInfo param, @WebParam(targetNamespace="http://www.informatica.com/wsh",
      partName="Context", name="Context", header=true)
    SessionHeader Context)
    throws Fault;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.informatica.com/wsh/MetadataInterface/GetAllTaskInstancesRequest", fault =
      { @FaultAction(value="http://www.informatica.com/wsh/MetadataInterface/getAllTaskInstances/Fault/Fault",
          className = Fault.class) }, output="http://www.informatica.com/wsh/MetadataInterface/GetAllTaskInstancesResponse")
  @WebResult(targetNamespace="http://www.informatica.com/wsh", partName="param",
    name="GetAllTaskInstancesReturn")
  public com.informatica.wsh.TaskInstanceInfoArray getAllTaskInstances(@WebParam(targetNamespace="http://www.informatica.com/wsh",
      partName="param", name="GetAllTaskInstances")
    com.informatica.wsh.GetAllTaskInstancesRequest param,
    @WebParam(targetNamespace="http://www.informatica.com/wsh", partName="Context",
      name="Context", header=true)
    SessionHeader Context)
    throws Fault;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.informatica.com/wsh/MetadataInterface/GetAllDIServersRequest", fault =
      { @FaultAction(value="http://www.informatica.com/wsh/MetadataInterface/getAllDIServers/Fault/Fault",
          className = Fault.class) }, output="http://www.informatica.com/wsh/MetadataInterface/GetAllDIServersResponse")
  @WebResult(targetNamespace="http://www.informatica.com/wsh", partName="param",
    name="GetAllDIServersReturn")
  public com.informatica.wsh.DIServerInfoArray getAllDIServers(@WebParam(targetNamespace="http://www.informatica.com/wsh",
      partName="param", name="GetAllDIServers")
    VoidRequest param, @WebParam(targetNamespace="http://www.informatica.com/wsh",
      partName="Context", name="Context", header=true)
    SessionHeader Context)
    throws Fault;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.informatica.com/wsh/MetadataInterface/GetAllRepositoriesRequest", fault =
      { @FaultAction(value="http://www.informatica.com/wsh/MetadataInterface/getAllRepositories/Fault/Fault",
          className = Fault.class) }, output="http://www.informatica.com/wsh/MetadataInterface/GetAllRepositoriesResponse")
  @WebResult(targetNamespace="http://www.informatica.com/wsh", partName="param",
    name="GetAllRepositoriesReturn")
  public com.informatica.wsh.RepositoryInfoArray getAllRepositories(@WebParam(targetNamespace="http://www.informatica.com/wsh",
      partName="param", name="GetAllRepositories")
    VoidRequest param)
    throws Fault;
}
