package com.informatica.wsh;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebServiceClient(wsdlLocation="http://someserver.somewhere.nl:7333/wsh/services/Metadata?wsdl",
  targetNamespace="http://www.informatica.com/wsh", name="MetadataService")
public class MetadataService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.informatica.wsh.MetadataService");
      URL baseUrl = MetadataService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            MetadataService.class.getResource("http://someserver.somewhere.nl:7333/wsh/services/Metadata?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://someserver.somewhere.nl:7333/wsh/services/Metadata?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://someserver.somewhere.nl:7333/wsh/services/Metadata?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://someserver.somewhere.nl:7333/wsh/services/Metadata?wsdl",
          e);
    }
  }

  public MetadataService()
  {
    super(wsdlLocationURL,
          new QName("http://www.informatica.com/wsh", "MetadataService"));
  }

  public MetadataService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="Metadata")
  public com.informatica.wsh.MetadataInterface getMetadata()
  {
    return (com.informatica.wsh.MetadataInterface) super.getPort(new QName("http://www.informatica.com/wsh",
                                                                           "Metadata"),
                                                                 com.informatica.wsh.MetadataInterface.class);
  }

  @WebEndpoint(name="Metadata")
  public com.informatica.wsh.MetadataInterface getMetadata(WebServiceFeature... features)
  {
    return (com.informatica.wsh.MetadataInterface) super.getPort(new QName("http://www.informatica.com/wsh",
                                                                           "Metadata"),
                                                                 com.informatica.wsh.MetadataInterface.class,
                                                                 features);
  }
}
